### ISSUE TITLE
Scalang doesn't build on the raspberri pi

### ISSUE THREAD

**Issue by arturog** [arturog/scalang#1]
The build doesn't work on the raspberry pi

**Comment by curlycabbage** [comment]
Hi @arturog, thanks for making this thread, and thanks for helping me build your projects.

Overlock, Scala and Clouseau build steps, from https://github.com/cloudant-labs/clouseau/issues/22:

```
mkdir /tmp/scalang_2.13
cd /tmp/scalang_2.13
git clone https://github.com/arturog/overlock.git
cd overlock
mvn install:install-file -Dfile=./target/overlock-scala_2.13-0.9.0-SNAPSHOT.jar -DpomFile=./pom.xml

cd /tmp/scalang_2.13
git clone https://github.com/arturog/scalang.git
git checkout scala-2-13
mvn verify

cd /tmp
git clone https://github.com/arturog/clouseau
cd clouseau
git checkout scala-2-13
mvn scala:run
```

Ok, so I think this is actually eliding a few steps:

1. before `mvn install:install-file -Dfile=./target/overlock-scala_2.13-0.9.0-SNAPSHOT.jar -DpomFile=./pom.xml`, we need `mvn package` (or maybe `mvn verify`?)
2. between `git clone https://github.com/arturog/scalang.git` and `git checkout scala-2-13`, we need `cd scalang`
3. after `mvn verify` for scala-2-13, we need `mvn install:install-file -Dfile=./target/scalang-scala_2.13-0.40-SNAPSHOT.jar -DpomFile=./pom.xml`

Updated instructions:

```
mkdir /tmp/scalang_2.13
cd /tmp/scalang_2.13
git clone https://github.com/arturog/overlock.git
cd overlock
mvn package
mvn install:install-file -Dfile=./target/overlock-scala_2.13-0.9.0-SNAPSHOT.jar -DpomFile=./pom.xml

cd /tmp/scalang_2.13
git clone https://github.com/arturog/scalang.git
cd scalang
git checkout scala-2-13
mvn verify
mvn install:install-file -Dfile=./target/scalang-scala_2.13-0.40-SNAPSHOT.jar -DpomFile=./pom.xml

cd /tmp
git clone https://github.com/arturog/clouseau
cd clouseau
git checkout scala-2-13
mvn scala:run
```

And with that, clouseau runs successfully on my pi. Yay! Haven't tested clouseau from dreyfus yet. That would be next. And there are lots of deprecation warnings in the overlock build and the scala build.

Does all this look about right to you, @arturog?

Btw, I am told by Will Holley on the CouchDB slack channel that "you can run clouseau using Java 8 - you just can’t compile it" [link](https://couchdb.slack.com/archives/C49LEE7NW/p1574668655358900)

**Comment by arturog** [comment]
Great it works!

I have been running this version of closeau against CouchDB master on a demo system and it has been OK so far.  I plan to release it in s production system of mine soon.

I am yet to finish with patches but I just been drowned with work and no time. Next step is to remove deprecations and get any failed tests passing. Feel free to chip in!

**Comment by arturog** [comment]
Closing this issue as instructions above from @curlycabbage work.
